apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia2
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: go1323/kubia_2
