apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  namespace: custom-namespace
spec:
  containers:
  - image: go1323/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
      